NCxJLu/NCxJLu/urls.py
# -*- coding: utf-8 -*-
"""NCxJLu URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
# 处理静态文件
from django.views.generic import TemplateView
from users.views import LoginView
from users.views import LogoutView
from users.views import RegisterView
from users.views import ActiveUserView
from users.views import ForgetPwdView
from users.views import ResetView
from users.views import ModifyPwdView
from  organization.views import OrgListView

from NCxJLu.settings import MEDIA_ROOT,STATIC_ROOT

import xadmin


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),

    # 根目录前面不加‘/’
    url(r'^login/',LoginView.as_view(),name='login'),

    url(r'^logout/', LogoutView.as_view(), name='logout'),

    url(r'^index/$',TemplateView.as_view(template_name='index.html'),name='index'),

    url(r'^$',TemplateView.as_view(template_name='page.html'),name='page'),

    url(r'^register/',RegisterView.as_view(),name='register'),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name='active'),

    url(r'^forgetpwd/$', ForgetPwdView.as_view(),name='forgetpwd'),

    url(r'^reset/(?P<reset_code>.*)/$',ResetView.as_view(),name='reset'),

    url(r'^modify_pwd/$', ModifyPwdView.as_view(),name='modify_pwd'),

    #课程机构首页
    url(r'^org_list/', include('organization.urls',namespace='org_list')),

    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$',serve, {"document_root":MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # 课程相关
    url(r'^course_list/', include('demos.urls', namespace='course_list')),

    # 讲师相关
    url(r'^teacher/', include('organization.urls', namespace='teacher_list')),

    # 用户中心
    url(r'^user/', include('users.urls', namespace='user')),

]

# 配置404
handler404 = 'users.views.page_no_found'
handler500 = 'users.views.page_error'

NCxJLu/apps/demos/urls.py
# -*- coding: utf-8 -*-
__author__ = 'wx'
__date__ = '17-3-7 下午 4:04'

from django.conf.urls import url,include
from .views import *

#{% url 'course_list:xxxxx' %}

urlpatterns = [

    url(r'^$', CouserListView.as_view(), name='course'),

    url(r'^detail/(?P<demo_id>\d+)/$', CouserDetailView.as_view(), name='detail'),

    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),

    url(r'^info/(?P<demo_id>\d+)/$', CouserVideoView.as_view(), name='info'),

    url(r'^comment/(?P<demo_id>\d+)/$', CommentsView.as_view(), name='comment'),

    url(r'^add_comment/$',AddCommentView.as_view(),name='add_comment'),

    url(r'^video/(?P<video_id>\d+)/$',CouserVideoPlayView.as_view(),name='video_play'),

]

NCxJLu/apps/users/urls.py
# -*- coding: utf-8 -*-
__author__ = 'wx'
__date__ = '17-3-19 下午 3:35'

from django.conf.urls import url,include

from .views import *

#{% url 'user':xxxxx %}

urlpatterns = [

    # 用户个人中心首页
    url(r'^info/$', UserInfoView.as_view(),name='info'),

    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(),name='image_upload'),

    # 用户修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(),name='update_pwd'),

    # 我的课程
    url(r'^my/couser/$', MyCouserView.as_view(), name='my_couser'),

    # 我的收藏机构
    url(r'^my/fav/org/$', MyFavOrgView.as_view(), name='my_fav_org'),

    # 我的收藏课程
    url(r'^my/fav/course/$', MyFavCourseView.as_view(), name='my_fav_course'),

    # 我的收藏教师
    url(r'^my/fav/teacher/$', MyFavTeacherView.as_view(), name='my_fav_teacher'),

    # 我的消息
    url(r'^my/message/$', MyMessageView.as_view(), name='my_message'),
]

NCxJLu/apps/demos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.db import models

from organization.models import CourseOrg,Teacher

# Create your models here.


class Demo(models.Model):
    teacher = models.ForeignKey(Teacher,verbose_name=u'授课教师',null=True,blank=True)
    Course_Org = models.ForeignKey(CourseOrg,verbose_name=u'课程机构',null=True,blank=True)
    name = models.CharField(max_length=100,verbose_name=u'案例名')
    desc = models.CharField(max_length=1000,verbose_name=u'案例描述')
    detail = models.TextField(verbose_name=u'案例详情')
    degree = models.CharField(verbose_name=u'难度',choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')),max_length=6)
    learn_time = models.IntegerField(default=0,verbose_name=u'学习时长')
    students = models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0,verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='image/%Y/%m',verbose_name=u'视频封面',max_length=100,null=True,blank=True)
    click_num = models.IntegerField(verbose_name=u'点击数',default=0)
    category = models.CharField(max_length=100,verbose_name=u'课程类别',null=True,blank=True)
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    tag = models.CharField(default='',verbose_name=u'课程标签',max_length=100)
    you_need_know = models.CharField(default= '',verbose_name=u"你需要知道",max_length=300,null=True,blank=True)
    teacher_tell = models.CharField(default='',verbose_name=u"老师告诉你",max_length=300,null=True,blank=True)

    class Meta:
        verbose_name = u'案例'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return  self.name

    def get_zj_num(self):
        # 获取章节数
        return self.lesson_set.all().count()

    def get_learn_user(self):
        # 获取学习课程用户
        return  self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        # 获取章节
        return self.lesson_set.all()


# Demo和Lesson为1对多关系，采用外键形式建立表
class Lesson(models.Model):
    demo = models.ForeignKey(Demo,verbose_name=u'案例')
    name = models.CharField(max_length=100,verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return  self.name

    def get_lesson_video(self):
        # 获取章节视频
        return self.video_set.all()


# Lesson和Video为1对多关系，采用外键形式建立表
class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    url = models.CharField(max_length=500,verbose_name=u'访问地址',default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    learn_time = models.IntegerField(default=0,verbose_name=u'学习时长')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return  self.name


# Demo和DemoResource为1对多关系，采用外键形式建立表
class DemoResource(models.Model):
    demo = models.ForeignKey(Demo,verbose_name='案例')
    name = models.CharField(max_length=100, verbose_name='视频资源名')
    downlaod = models.FileField(upload_to='demo/resource/%Y/%m',verbose_name=u'资源文件',max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'案例资源'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return  self.name

NCxJLu/apps/users/forms.py
# -*- coding: utf-8 -*-
__author__ = 'wx'
__date__ = '17-2-10 下午 2:04'
from django import forms
from captcha.fields import CaptchaField

from .models import UserProflie


class LoginForm(forms.Form):
    # username 不能为空
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True)
    captcha = CaptchaField(error_messages={'invalid':u'验证码错误'})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid':u'验证码错误'})


class ModifyPwdForm(forms.Form):
    password = forms.CharField(required=True)
    password2 = forms.CharField(required=True)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProflie
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProflie
        fields = ['mobile','nick_name','gender','birday','address']

NCxJLu/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>链接失效</h1>
</body>
</html>

NCxJLu/templates/course-list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}课程列表-NC在线首页{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}

<section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% ifequal sort '' %}active{% endifequal %}"><a href="?sort=">最新 </a></li>
						<li class="{% ifequal sort 'hot' %}active{% endifequal %}"><a href="?sort=hot">最热门</a></li>
						<li class="{% ifequal sort 'students' %}active{% endifequal %}"><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">

                        {% for demo in all_demo.object_list %}

                            <div class="box">
                                <a href="{% url 'course_list:detail' demo.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="/media/{{ demo.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course_list:detail' demo.id %}">
                                        <h2>{{ demo.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ demo.learn_time }}</i></span>
                                    <span class="fr">学习人数：{{ demo.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="course-detail.html"><span class="fl">来自{{ demo.Course_Org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ demo.fav_nums }}
                                    </span>
                                </div>
                            </div>

                        {% endfor %}

					</div>
                     <div class="pageturn">
                    <ul class="pagelist">

                 {% if all_demo.has_previous %}
                    <li class="long"><a href="?{{ all_demo.previous_page_number.querystring }}">上一页</a></li>
                 {% endif %}
                 {% for page in all_demo.pages %}
                    {% if page %}
                        {% ifequal page all_demo.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if all_demo.has_next %}
                    <li class="long"><a href="?{{ all_demo.next_page_number.querystring }}">下一页</a></li>
                {% endif %}


            </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">

                    {% for demo in hot_demo %}
                    <dl>
						<dt>
							<a target="_blank" href="{% url 'course_list:detail' demo.id %}">
								<img width="240" height="220" class="scrollLoading" src="/media/{{ demo.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2>{{ demo.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ demo.get_degree_display }}</i></span>
						</dd>
					</dl>
                    {% endfor %}



				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

<!--crumbs start-->

NCxJLu/templates/course-play.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课视频 - NC Online{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course_list:course' %}">公开课程</a>></li>
				<li><a href="{% url 'course_list:detail' demo.id %}">课程详情</a>></li>
                <li>章节信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}

    <div id="main">
    <div style="width:1200px;height:675px;margin-left:40px">
        <video id='example_video_1' class="video-js vjs-defult-skin" controls="" preload="none" width="1200"
                poster="http://video-js.zencoder.com/ocean-clip.png"
                data-setup="{}">
                <source src="/media/{{ video.url }}" type="video/mp4">

        </video>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course_list:info' demo.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course_list:comment' demo.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for lession in demo.get_course_lesson %}
                     <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lession.name }}</strong>
                        </h3>
                        <ul class="video">
                        {% for video in lession.get_lesson_video %}
                            <li>
                                <a target="_blank" href='/video/3662' class="J-media-item studyvideo">{{ video.name }}({{ video.learn_time }})
                                    <i class="study-state"></i>
                                </a>
                            </li>
                        {% endfor %}

                        </ul>
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resourse in all_resourse %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>{{ resourse.name }}</span>
                                <a href="/media/{{ resourse.downlaod }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='/media/{{ demo.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ demo.teacher.name }}</a>
        </span>
                            <span class="job">{{ demo.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ demo.you_need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ demo.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">

                                    {% for course in  relate_courses %}
                                    <li class="curr">
                                        <a href="{% url 'course_list:detail' course.id %}" target="_blank">
                                            <img src="/media/{{ course.image }}" alt="{{ course.name }}">
                                            <span class="name autowrap">{{ course.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}


                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.cs' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/video-js.min.css' %}">

    <style type="text/css">

	.video-js .vjs-big-play-button{
		top: 50%;
		left:50%;
	}
    </style>
{% endblock %}
{% block custom_js %}
    <link rel="stylesheet" type="text/css" href="{% static 'js/video.min.js' %}">
{% endblock %}

NCxJLu/templates/org-detail-course.html
{% extends 'org_base.html' %}
{% load staticfiles %}
{% block title %}机构课程{% endblock %}
{% block page_path %}机构课程{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
		<div class="head">
			<h1>机构课程</h1>
		</div>
		<div class="brief group_list">
                {% for demo in all_demo.object_list %}
                <div class="module1_5 box">
                    <a class="comp-img-box" href="{% url 'course_list:detail' demo.id %}">

                        <img width="214" height="195" src="/media/{{ demo.image }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url 'course_list:detail' demo.id %}"><h2>{{ demo.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ demo.learn_time }}</i></span>
                        <span class="fr">学习人数：{{ demo.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ demo.Course_Org.name }}</span>
                         <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            {{ demo.fav_nums }}
                        </span>
                    </div>
                </div>
                {% endfor %}

		</div>
			 <div class="pageturn">
                <ul class="pagelist">

                 {% if all_demo.has_previous %}
                    <li class="long"><a href="?{{ all_demo.previous_page_number.querystring }}">上一页</a></li>
                 {% endif %}
                 {% for page in all_demo.pages %}
                    {% if page %}
                        {% ifequal page all_demo.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if all_demo.has_next %}
                    <li class="long"><a href="?{{ all_demo.next_page_number.querystring }}">下一页</a></li>
                {% endif %}


            </ul>
            </div>
	    </div>
{% endblock %}

NCxJLu/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>邮寄发送成功</title>
</head>
<body>
<h1>邮件已发送，请查收</h1>

</body>
</html>

NCxJLu/templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}收藏课程--NC Online{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="/user/home/">个人中心</a>></li>
            <li>收藏课程</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}

    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:my_fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:my_fav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'user:my_fav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                    {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course_list:detail' course.id %}">
                                <img width="214" height="190" src="/media/{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ couser.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ couser.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ couser.Course_Org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}

                    </div>
                </div>
            </div>
        </div>


{% endblock %}

NCxJLu/templates/usercenter-info.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}个人信息--NC Online{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="/user/home/">个人中心</a>></li>
            <li>个人信息</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
<div class="right">
    <div class="personal_des ">
        <div class="head" style="border:1px solid #eaeaea;">
            <h1>个人信息</h1>
        </div>
        <div class="inforcon">
            <div class="left" style="width:242px;">
                <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'user:image_upload' %}" target='frameFile'>
                    <label class="changearea" for="avatarUp">
                        <span id="avatardiv" class="pic">
                            <img width="100" height="100" class="js-img-show" id="avatarShow" src="/media/{{ request.user.image }}"/>
                        </span>
                        <span class="fl upload-inp-box" style="margin-left:70px;">
                            <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                            <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                        </span>
                    </label>
                   {% csrf_token %}
                </form>
                <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                    <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                </div>
            </div>
            <form class="perinform" id="jsEditUserForm" autocomplete="off">
                <ul class="right">
                    <li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                       <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                        <i class="error-tips"></i>
                    </li>
                    <li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                       <input type="text" id="birth_day" name="birday" value="{{ request.user.birday }}" readonly="readonly"/>
                        <i class="error-tips"></i>
                    </li>
                    <li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %} checked="checked"{% endif %} >男</label>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
                    </li>
                    <li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                        <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
                        <i class="error-tips"></i>
                    </li>
                    <li>手&nbsp;机&nbsp;号：
                        <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile }}" maxlength="10">
                    </li>
                    <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        <input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                        <span class="green changeemai_btn">[修改]</span>
                    </li>
                    <li class="button heibtn">
                        <input type="button" id="jsEditUserBtn" value="保存">
                    </li>
                </ul>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}